version: '3.8'

services:
  producer:
    build: ./producer
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_VIRTUAL_HOST=/
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest

  consumer_one:
    build: ./consumer_one
    depends_on:
      - rabbitmq
 
  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:

